<p>Version 1.0 in effect from November 22nd 2019.
        THIS IS A LONG DOCUMENT CONTAINING SEVERAL IMPORTANT CLAUSES THAT RELATE TO YOUR RIGHTS AND OBLIGATIONS. BY USING THE WEBSITE ACCESSIBLE AT THE ADDRESSES WWW.HIHOME.sa AND ON HIHOME’S MOBILE APPS. THE CHARTER AND TERMS ARE COLLECTIVELY REFERRED TO AS THE MASTER AGREEMENT. WE WOULD ADVISE YOU TO PRINT A COPY OF THE MASTER AGREEMENT FOR YOUR RECORDS.</p>
        <h4>1. Introduction</h4>
        <p>1.1 Hihome company Limited (“Hihome”) is a private limited company incorporated under the laws of The kingdom of Saudi Arabia with the name “Hihome company Limited” under  number 357507 and whose registered office address in Abu Humdain street, Riyadh, Saudi Arabia</p>
        <p>1.2 Hihome operates websites, social media channels, APIs and applications (“Hihome Websites”) and provides a platform, services and market place by which users may issue invitations (the “Hihome Invitations”) offering to host or provide meals (or other social dining experiences) which others may accept.</p>

        <p>1.3 Your use of the Hihome Websites and the services offered by Hihome (the “Hihome Services”) is governed by these terms and conditions set out in this document and the documents referred to in this document (together the “T&Cs”).</p>
        <p>1.4 In these T&Cs users who issue Hihome Invitations are (in that capacity) referred to as “Hosts” and users who accept Hihome Invitations are referred to (in that capacity) as “Guests”.A single user may be either a Host or a Guest in relation to different Hosted Events.Hihome offers an international marketplace allowing Hosts and Guests the opportunity to contract each other.</p>
        <p>1.5 Unless Hihome expressly agrees to the contrary in writing, all your dealings with Hihome will be on and subject to the terms of these T&Cs.By using the Hihome Websites and the Hihome Services, you agree to be bound by these T&Cs.</p>
        <p>1.6 These T&Cs may be updated from time to time, updates will be posted on the Hihome website and we shall endeavour to notify registered users of updates, it is however your responsibility to ensure that you remain compliant with the current T&Cs from time to time.We may also modify the operation of the Hihome Services and the amounts charged and payment mechanisms.These changes will not have retrospective application.If the modified T&Cs are not acceptable to you, your only recourse is to cease using the Hihome Websites and Hihome Services. If you do not cancel your Hihome registration you will be deemed to have accepted the changes.</p>
        <p>1.7 Subject to your compliance with these T&Cs, Hihome grants you a limited non-exclusive, non-transferable license to download and install a copy of the applications forming a part of the Hihome Websites on each mobile device or computer that you own or control and run that application solely for your own personal use. You agree to adhere, in addition to these T&Cs, to the terms and conditions applicable to the device on which you run the application and store from which you download it. Hihome reserves all rights in the application not expressly granted to you by these T&Cs.</p>
        <p>1.8 If you do not agree to be bound by these T&Cs, you may not use the Hihome Websites or Hihome Services.</p>
        <h4>2. Registration</h4>
        <p>2.1 Unregistered visitors may view the Hihome Websites.Only registered users may post content on the Hihome Websites and issue or accept Hihome Invitations.Registered users are identified on the Hihome Website by their first name and registered city and country.Hihome may rank or rate registered users.As a user you represent to Hihome that you will only use the Hihome Websites and Hihome Services for lawful purposes and where it is lawful to so use them.</p>
        <p>2.2 You acknowledge and agree that, by accessing or using the Hihome Websites or Hihome Services or by downloading or posting any content to or from the Hihome Websites you are indicating that you have read, and that you understand and agree to be bound by these T&Cs. If you accept or agree to these T&Cs on behalf of a company or other legal entity, you represent and warrant that you have the authority to bind that company or other legal entity to these T&Cs and, in such event, “you” and “your” will refer and apply to that company or other legal entity.</p>
        <p>2.3 By registering with Hihome you agree to adhere to (i) public policies published by Hihome on the Hihome Websites (such as the privacy policy), and (ii) the “Guest’s Charter” in respect of any Hihome Invitations that you accept, and (iii) the “Host’s Charter” in respect of any Hihome Invitations you issue.You may cancel your registration at any time by following the instructions on the Hihome Websites.If you cancel your registration we shall delete all personally identifiable information to the extent required to comply with applicable laws. You accept that we may terminate any user’s registration at any time.</p>
        <p>2.4 Registration and access to the Hihome Services are intended solely for persons who are 18 or older. Any access or use of the Hihome Websites or Hihome Services by anyone under 18 is expressly prohibited. By using the Hihome Websites and Hihome Services you represent and warrant that you are aged 18 years or older.</p>
        <p>2.5 You agree to compete the registration process honestly and as completely as you are able, and to keep the registration and other information about you accurate and up-to-date.You may maintain only one registration with Hihome, and may not register as a Hihome user on behalf of an individual other than yourself.Your registration with Hihome is personal to you and may not be sold or transferred without Hihome’s prior written agreement.You agree never to disclose your login details or password (except for the purpose of your logging in to the Hihome Websites yourself).</p>
        <p>2.6 By registering as a user with Hihome you agree that Hihome may request consumer, credit rating and similar reports on you.If Hihome requests any such report, it will request and use it in compliance with applicable law.</p>
        <p>2.7 If you link your registration with an accepted third-party social networking site or service you represent that you are lawfully able to do so and that such linking complies with all terms you and the third party have agreed and will not result in Hihome incurring any obligations or liabilities.</p>
        <p>2.8 You will need to agree to our payment provider’s terms and conditions when you register to make or receive payments.</p>
        <h4>3. Our content and your use of the Hihome Website</h4>
        <p>3.1 Apart from the content generated by registered users, all the elements that make up the Hihome Websites and Hihome Services (including, without limiting the generality of this provision, its content, graphics, applications, software, functions and other features) belong to Hihome (or the person from whom Hihome licenses it).You agree that you have no entitlement to any part of the Hihome Websites or Hihome Services otherwise than to view content and use the communications facilities in connection with arranging and promoting Hosted Events and issuing, accepting and paying for Hihome Invitations in accordance, in each case, with these T&Cs.You agree that you are not permitted to reproduce, distribute, emulate, publish or imitate any part of the Hihome Websites and Hihome Services without Hihome’s prior written agreement.</p>
        <p>3.2 In using the Hihome Website and Hihome Services you agree that you will not:</p>
        <ul>
            <li>3.2.1 Circumvent Hihome’s legitimate commercial interests by participating in a transaction related to a Hosted Event independent of the Hihome Websites and Hihome Services or take any action (other than publish genuine reviews) to dilute, tarnish or otherwise harm the Hihome brand in any way;</li>
            <li>3.2.2 Use any part of the Hihome Website or Hihome Services for any commercial or other purposes that are not expressly permitted by these T&Cs or in a manner that falsely implies Hihome endorsement, partnership or otherwise misleads others as to your affiliation with Hihome or any of its users or partners;</li>
            <li>3.2.3 Use manual or automated software, devices, scripts, robots, backdoors or other means or processes to (i) access, “scrape,” “crawl” or “spider” any web pages or other services contained in the Hihome Website and Hihome Services, or (ii) collect information from or otherwise interact with Hihome Website or Hihome Services, or (iii) systematically retrieve data or other content from any of the Hihome Websites to create or compile, directly or indirectly, in single or multiple downloads, a compilation, database, directory or similar or analogous collection of information, or (iv) access, tamper with, or use non-public areas of any of the Hihome Websites and Hihome Services or the technical delivery systems of Hihome’s partners, or (v) attempt to probe, scan, or test the vulnerability of any part of any of the Hihome Websites or Hihome’s Services or Hihome’s security or authentication measures, or (vi) damage, disable, overload or alter any part of the Hihome Website or any other website, application or electronic communication, or (vii) broadcast any element containing computer viruses or any code, file, or computer program designed to interrupt, destroy or limit the software, features, IT or telecommunication equipment;</li>
            <li>3.2.4 Access or use any of the Hihome Website or Hihome Services (i) to use, expose, or allow to be used or exposed, any content that is not publicly displayed by Hihome in its search results pages or listing pages before a Hihome Invitation is accepted; or (ii) in any way that is inconsistent with these T&Cs or any privacy or other policy publicly adopted by Hihome; or (iii) in any way that violates the privacy or any other rights of any other of Hihome’s users or any other third party;</li>
            <li>3.2.5 Register and/or use any intellectual property of Hihome (or persons from which it licences intellectual property) or in the name “Hihome” or its logo (or derivative terms or terms that are confusingly similar) whether in any domain names, trade names, trademarks or other source identifiers, trademarks, taglines, promotional campaigns or otherwise or infringe the rights of Hihome or the rights of any other person or entity (including, without limiting the generality of this provision, any intellectual property, privacy, publicity or contractual rights);</li>
            <li>3.2.6 Copy, store or otherwise access or use any information contained on any of the Hihome Websites for purposes not expressly permitted by these T&Cs or use, display, mirror or frame the any of the Hihome Websites or Hihome Services, or any individual element within the any of the Hihome Websites or Hihome Services, Hihome’s name, any Hihome trademark, logo or other proprietary information, or the layout and design of any page or form contained on a page in the Hihome Websites and Hihome Services, without Hihome’s express written consent;</li>
            <li>3.2.7 Interfere with or damage any of the Hihome Websites or Hihome Services (including, without limiting the generality of this provision, by the use of viruses, cancel bots, Trojan horses, harmful code, flood pings, denial-of-service attacks, backdoors, packet or IP spoofing, forged routing or electronic mail address information or similar methods or technology) or in connection with the distribution of unsolicited emails or advertisements (other than Hihome Invitations);</li>
            <li>3.2.8 “Stalk” or harass any other user of any of the Hihome Websites or Hihome Services, or collect or store any personally identifiable information about any other user (other than for purposes of transacting as a Guest or Host);</li>
            <li>3.2.9 Contact any Hihome user otherwise than about a Hihome Invitation;</li>
            <li>3.2.10 Recruit or otherwise solicit any Hihome user to join a third-party service or website whether or not it is competitive to Hihome, without Hihome’s prior written approval;</li>
            <li>3.2.11 Avoid, bypass, remove, deactivate, impair, scramble, descramble, or otherwise circumvent any technological measure implemented by Hihome or any of Hihome’s providers or any other third party (including another user) to protect any part of the Hihome Websites or Hihome Services, forge any TCP/IP packet header or any part of the header information in any email or newsgroup posting, or in any way use any part of any of the Hihome Websites or Hihome Services to send altered, deceptive or false source-identifying information or attempt to decipher, decompile, disassemble or reverse engineer any of the software used to provide the any part of any of the Hihome Websites or Hihome Services;</li>
            <li>3.2.12 Advocate, encourage, or assist any third party in doing any of the foregoing.</li>
        </ul>
        <p>3.3 You agree not to remove, alter or obscure any copyright, trademark, service mark or other proprietary rights notices incorporated in or accompanying the Hihome Websites, Hihome Services and ancillary documentation. You also agree not to use, copy, adapt, modify, prepare derivative works based upon, distribute, license, sell, transfer, publicly display, publicly perform, transmit, broadcast or otherwise exploit the Hihome Website or Hihome Services except as expressly permitted in these T&Cs. No licenses or rights are granted to you by implication or otherwise under any intellectual property rights owned or controlled by Hihome or its licensors, except for the licenses and rights expressly granted in these T&Cs.</p>
        <h4>4. Your Content</h4>
        <p>4.1 Registered users may post content on the Hihome Websites. Anything that you post (or otherwise cause to be visible) on a Hihome Website is deemed for the purposes of these T&Cs to be content published by you (“Your Content”).Hihome’s policy is not to edit or moderate Your Content unless required to do so to ensure compliance with these T&Cs or with your prior consent.You agree that if you have linked your Hihome registration with any third-party service, the services may exchange information and you shall be deemed to have published any information made available by the third-party service as a result of the accounts being linked.</p>
        <p>4.2 You are responsible for all Your Content. By registering to use the Hihome Websites you agree that:</p>
        <ul>
            <li>4.2.1 Any representation that you publish is true;</li>
            <li>4.2.2 You shall not use the Hihome Websites or Hihome Services to offer products or services other than Hihome experience</li>
            <li>4.2.3 You shall not post, upload, publish, submit or transmit anything that: (i) infringes, misappropriates or violates a third party’s patent, copyright, trademark, trade secret, moral rights or other intellectual property rights, or rights of publicity or privacy or rights to an image; or (ii) violates, or encourages any conduct that would violate, any applicable law or regulation or would give rise to civil or criminal liability or might be expected to incite any anti-social behaviour; or (iii) is fraudulent, false, misleading (directly or by omission or failure to update information) or deceptive; or (iv) is defamatory, abusive, threatening, harassing or obscene, pornographic, vulgar or may otherwise be found to be offensive by a reasonable person; or (v) is discriminatory, prejudicially intolerant, racist, hate inspired, harassing or harmful toward any individual or group, anti-Semitic, paedophilic, inciting violence, racial or ethnic hatred, illegal or that is in any other way reprehensible; or (vi) is violent or threatening or promotes violence or actions that are threatening to any person or group; or (vii) promotes illegal or harmful activities or substances; or (viii) condones or promotes any of the things listed in (i) to (vii);</li>
            <li>4.2.4 None of Your Content shall include any images which you do not own or which include or depict any identifiable person who has not consented to the use of the image (and, in the case of images taken at a Hosted Event, in respect of which the relevant Host has consented to you publishing);</li>
            <li>4.2.5 You shall not use the Hihome Website or Hihome Services to (i) transmit, distribute, post or submit any information concerning any other person or entity (including, without limiting the generality of this provision, photographs, contact or sensitive information or credit, debit, banking or other account numbers) without the relevant person’s prior permission; or (ii) impersonate any person or entity, or falsify or otherwise misrepresent yourself or your affiliation with any person or entity;</li>
            <li>4.2.6 All Your Content may be made public and associated with you;</li>
            <li>4.2.7 Hihome is under no obligation to store and/or to publish Your Content (and Hihome may at any time and without prior notice delete Your Content from any part of the Hihome Website);</li>
            <li>4.2.8 Although you remain the owner of (and responsible for) Your Content, nothing in any relationship between you and Hihome operates to transfer any intellectual property rights to you;</li>
            <li>4.2.9 You grant (or shall procure the grant) to Hihome of a worldwide, non- exclusive, transferable, sub-licensable, royalty-free license to use all content (and all related intellectual property) in any content made available by you on the Hihome Website;</li>
            <li>4.2.10 Hihome may edit, reproduce (in whole or in part), translate, link to and from, group and otherwise deal with Your Content (or elements of it) as it deems appropriate;</li>
            <li>4.2.11 Hihome may use and exploit Your Content (and information that Hihome learns about you) to communicate with you, target advertising to you and develop, implement and refine marketing campaigns and to promote Hihome’s Services generally;</li>
            <li>4.2.12 You shall not advocate, encourage, or assist any third party in doing any of the foregoing.</li>
            
        </ul>
        <p>4.3 You agree that any profile photograph that you upload is an honest representation of you and does not infringe any intellectual property rights belonging to a third party and that you expressly authorize Hihome to use your image.</p>
        <p>4.4 By accepting these T&Cs you grant Hihome a worldwide, irrevocable, perpetual (or for the term of the protection), non-exclusive, transferable, royalty- free license, with the right to sublicense, to use, view, copy, adapt, translate, modify, distribute, license, sell, transfer, publicly display, publicly perform, transmit, stream, broadcast, access, view, and otherwise exploit Your Content (which may include publishing it on, through, by means of the Hihome Websites and Hihome Services and may also include promoting or marketing the Hihome Websites and Hihome Services). Hihome does not claim any ownership rights in Your Content and nothing in these T&Cs will be deemed to restrict any rights that you may have to use and exploit Your Content.</p>
        <p>4.5 Notwithstanding the licences granted to Hihome pursuant to clauses 4.2.8 and 4.3, Hihome shall use reasonable endeavours to remove such of Your Content as you request us to remove from our current Hihome Websites (the request to be made through your registered account and confirmed in a recorded delivery letter with signed proof of receipt including sufficient details for us to identify you and the relevant part of Your Content that you request is removed from the Hihome Websites).</p>
        <p>4.6 The Hihome Websites and Hihome Services may provide links or referrals to other websites, services, publications or applications. Hihome makes and gives no representation, endorsement, guarantee or confirmation as to the reliability of any such website, service publication or application and by agreeing to these T&Cs you agree that you shall not rely on Hihome when assessing or using them and that Hihome shall under no circumstance be responsible to you for any failure of any websites, services, publications or applications for which it is not responsible.Hihome assumes no responsibility for the content of websites linked on our site.Hihome will not be liable for any loss or damage that may arise from your use of them.In this context you confirm that Hihome is not responsible for the actions or failures of its payment providers.</p>
        <p>4.7 You agree and consent that Hihome may (but is not obliged to) employ translators and copy editors (and may apply automated translation and copy editing services) to Your Content to change the style or language used by you.Except to the extent that anything done by Hihome create an obligation or liability which would not otherwise have arisen, you agree that these processes shall not diminish any responsibility or liability you have for Your Content (and that you shall hold Hihome harmless from any loss it may suffer as a result of hosting or otherwise dealing with Your Content).</p>
        <h4>5. Data</h4>
        <p>5.1 By accepting these T&Cs you agree that Hihome may collate and analyse data resulting from your use of the Hihome Websites and Hihome Services and may use and sell the resulting information.</p>
        <p>5.2 Hihome will use reasonable endeavors to ensure that unless you agree to the contrary your personal information will not be disclosed to third parties except to the extent required to undertake reasonable verification, necessary to provide the Hihome Services or to operate the Hihome Website or as permitted by clause 5.3.</p>
        <p>5.3 You expressly grant us permission, without further notice, to store, transfer and disclose data and other information relating to you or to your transactions, including, but not limited to, personally identifiable information to any relevant tax or other governmental or competent regulatory or law enforcement authority or agency that claims to be entitled to such information.</p>
        <p>5.4 To the extent required by applicable law, Hihome shall on request of the relevant registered user delete all information that is personal to that registered user. Hihome may however (subject to applicable laws) retain data that may have been obtained by previous interactions with Hihome provided that that data cannot be linked to any individual person.</p>
        <p>5.5 Hihome reserves the right to market the results of this automatic data handling.</p>
        <p>5.6 You agree not to do anything to create a false impression that you are endorsed by, partnering with, or acting on behalf of or for the benefit of Hihome, including by inappropriately using any Hihome intellectual property.</p>
        <h4>6. Financial arrangements</h4>
        <p>6.1 When issuing Hihome Invitations Hosts state the fees that they will charge each Guest, these fees are quoted inclusive of all sales and analogous or other taxes (the “Host’s Charges”).Hihome arranges a service for these fees to be collected and held in a third-party trust account on terms that the funds will be paid in accordance with these T&Cs (arranging this collection and holding service constitutes a part of the Hihome Services).Hihome may charge Guests a fee for the use of the Hihome Services (the “Hihome Fees”).Acceptance of a Hihome Invitation constitutes agreement to pay the Host’s Charges and any Hihome Fees (the “Transaction Fees”).The total amount of the Transaction Fees is the amount payable by the Guest in respect of each Hihome Invitation at the time that the Guest accepts the Hihome Invitation.</p>
        <p>6.2 Where applicable, the Hihome Fees are calculated as a variable percentage of the Host’s Charges.Any Hihome Fees are payable by the Guests at the same time as payment of the Host’s Charges.To the extent that the Hihome Fees are subject to sales taxes, such as VAT, these taxes will be included in the total amount payable by the Guest in respect of the Transaction Fees. Where Hihome charges Hihome Fees it shall on request provide an invoice in respect of those Hihome Fees, separately identifying any sales taxes charged by Hihome.</p>
        <p>6.3 Hosts agree and acknowledge that they are responsible for discharging all of their own tax obligations (including sales taxes including, but not limited to, VAT) whether these are imposed on a state, local or other level. Hihome assumes no obligations whatsoever in this regard. In particular, Hihome assumes no responsibility (actual or deemed) to notify or explain to Hosts, or to enquire into, the VAT or sales taxes treatment of any Hosts or Hosted Events.</p>
        <p>6.4 If Hihome so requires for the purposes of its dealings with any tax or regulatory authority, Hosts and Guests shall provide to Hihome, promptly on request, any information, data, documentation and/or copies of communications (whether in electronic format or otherwise) which relate to Hosted Events in which they have participated. Hosts shall, promptly on request, provide to Hihome all reasonable assistance in any discussion or dispute with any tax authority with respect to the VAT or sales tax treatment of Hosted Events in which those Hosts have participated.Each Host agrees to indemnify Hihome for any VAT or similar sales tax obligations which Hihome is required to pay and which arise wholly from Hosted Events hosted by that Host.</p>
        <p>6.5 You may only make payments in respect of Hihome Invitations through the payment processing facilities provided on the Hihome Websites, by special arrangement with Hihome through its direct booking services or of through a third-party agency that is authorised by Hihome to provide those parts of the Hihome Services relating to processing payments.Please check with Hihome to ensure that any third-party with whom you are dealing is properly authorised by Hihome.If the Hihome Invitation is transacted through an authorised third-party you may not be required to pay any Hihome Fees, but the authorised third-party agent may instead charge an administration fee.</p>
        <p>6.6 You agree that the sole and exclusive role and responsibility of Hihome (and any of its authorised third-party agents) in providing Hihome Services relating to processing payments is to arrange the collection of payments from Guests and for the payment of the amounts collected in accordance with these T&Cs (and you agree that they have no other or further liability to you in respect of any payment made).</p>
        <p>6.7 Payments are made by Guests through selected payment providers.The terms on which the payment providers hold funds are stated in their terms.Hihome may receive amounts due to Hosts from payment providers, where it does so such funds will be held in a bank account until they are transferred to the Host (or, where appropriate, reimbursed to the Guest).</p>
        <p>6.8 Payment for the Hihome experiences should be completed at least 48 hours before the hosted event.</p>
        <p>6.9 Hihome may “round off” numbers to the nearest functional base unit in the relevant currency.Hihome uses commercial currency exchange operators and registered users accept the risks in fluctuations in currency exchange rates</p>
        <h4>7. Insurance, disputes, resolution and refunds</h4>
        <p>7.1 Guests may need to cancel a Hihome Invitation that they have previously accepted, in such cases please contact Hihome at info@Hihome.sa. Guests shall qualify for a full refund of the Host’s Charges if (a) the Guest notifies Hihome and the Host of cancellation during usual business hours in Riyadh (being 9am to 5pm on weekdays other than public holidays) at least 24 hours before the date on which the relevant Hosted Event is due, or (b) if the Host cancels the Hosted Event for any reason.</p>
        <p>7.2 We hope all Guests enjoy every Hosted Event, however sometimes things go wrong and if a Guest believes that the Host failed to fulfil an essential obligation of the Hosted Event then the Guest may until midnight on the day following the date on which the relevant Hosted Event was scheduled to take place request that the whole or a part of the payment is refunded by sending an email to info@Hihome.sa specifying the Hosted Event reference, identifying the Host, specifying the amount of the Transaction Fees, saying how much the Guest wishes to be reimbursed and giving as much information as possible in relation to the problem/ relevant failures/ reasons for believing that payment should be refunded.</p>
        <p>7.3 If you have a dispute relating to a Hosted Event, we encourage you (although this is not compulsory) to contact our claims department in order to try to resolve the dispute amicably. Our claims service can be contacted:</p>
        <ul>
            <li>By email at the following address: info@Hihome.sa</li>
            <li>By telephone on +966 505423361</li>
        </ul>
        <p>7.4 It is important that if, as a Guest, you are not satisfied with a Hosted Event you notify Hihome before midnight on the day following the date on which the relevant Hosted Event was scheduled to take place.Once Hihome has released funds to the Host, it is unable to offer Guests any remedy.</p>
        <p>7.5 Following receipt of a refund request Hihome may direct that an amount up to the entire value of the Transaction Fees paid by the Guest (less payment transaction costs and any third-party agency fees that Hihome is not entitled to recover) is refunded to the Guest.If, however, Hihome believes that the complaint is without merit, of limited merit or that Hihome is not able to assess the merit of the complaint, then Hihome may direct that the whole or any part of the Transaction Fees are paid to the Host and/ or that the balance (if any) is withheld pending resolution of the dispute between the relevant Host and the Guest.If no such resolution has been reached within six months, Hihome may direct that 50% of the disputed element of the Host’s Charges is paid to the Host and that 50% of the disputed element of the Host’s Charges is paid to the Guest (and the Hihome Fees shall be paid to Hihome) or may make such other arrangements as then appear appropriate to it (which may include making payment as directed by a Court of competent jurisdiction).Hihome shall have no further or other liability or responsibility to the Host and Guest in respect of any such claim to be refunded.You agree to abide by decisions made by Hihome (even if the decision appears perverse to you).</p>
        <p>7.6 Hihome agrees to use reasonable endeavours to assess merits of claims and to act in good faith toward Guests and Hosts, however you agree that it has no responsibility or liability to you for any assessment it makes in relation to the merits of any claim between Guests and Hosts or any direction it gives as to the payments to be made to Guests or Hosts in accordance with this clause 8 and you also agree that Hihome may make or decline refunds and payments pursuant to these T&Cs and that if and to the extent it does so it shall have no further liability or obligation to you or the Host or Guest.</p>
        <p>7.7 Hihome will endeavour to make refunds to Guests through the same payment facility through which the payment was originally made. Where it is not possible to make such a refund, it will may require other verification before the refund can be processed.The Guest agrees to bear the cost of currency exchanges and risks in fluctuations in currency exchange rates.</p>
        <p>7.8 By accepting these T&Cs you agree that if Hihome has followed the processes mentioned above in good faith it shall have no further or other liability or obligation to you.</p>
        <p>7.9 Hihome has no responsibility or liability in respect of any failing by a payment processor or authorised agent.</p>
        <p>7.10The Hihome platform serves as a trusted intermediary between Hosts and Guests and maintains itself through the service fee included in each Guests' booking. In the case that a Host or Guest offers payment alternatives outside of the platform, Hihome is no longer responsible and reserves the right to disable the Host's Hihome account.</p>
        <h4>8. Exclusions and limitations to Hihome’s responsibility and liability</h4>
        <p>8.1 You agree by issuing or accepting a Hihome Invitation you do not create any relationship with Hihome save as expressly provided in these T&Cs. Hihome does not control, and has no right to control, your Hihome Invitation, your offline activities associated with your Hihome Invitation, or any other matters related to any Hihome Invitation that you publish.</p>
        <p>8.2 Registered users are required by these T&Cs to provide accurate information about yourself and only to post reliable and accurate content to the Hihome Websites and not, when using the Hihome Websites or Hihome Services, to make any factually incorrect, fraudulent or misleading statements or representations.By accepting these T&Cs you agree that Hihome, its payment providers and/or other partners may request identity verification from you (and you agree to comply with such requests as are reasonable made) and may use other information or resources available to them to verify your identity, to undertake regulatory checks and to help limit improper use of the Hihome Websites, Hihome Services and other services provided by the payment providers and other partners.Hihome does not, however, undertake any obligation to you to undertake any such checks and you agree that Hihome does not represent, endorse, guarantee or confirm the identity of any user or the accuracy of any content or representation made by any user or otherwise received from (or communicated in connection with or as a result of) any of the Hihome Websites or Hihome Services (and by agreeing to these T&Cs you irrevocably agree that except to the extent otherwise expressly agreed by Hihome you waive any entitlement to claim reliance on any such representation, endorsement, guarantee or confirmation).</p>
        <p>8.3 To the extent permitted by law, Hihome excludes all conditions, warranties, representations or other terms which may apply to the Hihome Websites and Hihome Services or any content on them, whether express or implied. Hihome will not be liable to any user for any loss or damage, whether in contract, tort (including negligence), breach of statutory duty, or otherwise, even if foreseeable, arising under or in connection with:</p>
        <ul>
            <li>8.3.1 Use of, or inability to use, any of the Hihome Websites or Hihome Services;</li>
            <li>8.3.2 Use of or reliance on any content displayed on any of the Hihome Websites or Hihome Services.</li>
        </ul>
        <p>8.4 Subject as provided in clause 8.3, Hihome will not be liable for:</p>
        <ul>
            <li>8.4.1 Loss of profits, sales, business, or revenue;</li>
            <li>8.4.2 Business interruption;</li>
            <li>8.4.3 Loss of anticipated savings;</li>
            <li>8.4.4 Loss of business opportunity, goodwill or reputation;</li>
            <li>8.4.5 Any indirect or consequential loss or damage.</li>
        </ul>
        <p>8.5 Hihome will not be liable for any loss or damage caused by a virus, distributed denial-of-service attack, or other technologically harmful material that may infect your computer equipment, computer programs, data or other proprietary material due to your use of our site or to your downloading of any content on it, or on any website linked to it.</p>
        <p>8.6 By using the Hihome Websites and Hihome Services, you agree that (subject as provided in clause 8.3) any legal remedy or liability that you seek to obtain for actions or omissions of other users of the Hihome Websites and Hihome Services or other third parties will be limited to a claim against the individual or other third party who caused you harm.You agree not to attempt to impose liability on or seek any legal remedy from Hihome with respect to such actions or omissions.</p>
        <p>8.7 You agree that to the maximum extent permitted by law Hihome has no liability or responsibility to you in respect of any general or specific failure, suspension or interruption in any services offered by any of the Hihome Websites or error or omission in information or processing provided on or by the Hihome Websites or loss of information provided to the Hihome Websites.</p>
        <p>8.8 Nothing in these terms of use excludes or limits our liability for death or personal injury arising from our negligence, or our fraud or fraudulent misrepresentation, or any other liability that cannot be excluded or limited by Saudi Arabian law.</p>
        <p>8.9 Save to the extent that liability may not be excluded by law:</p>
        <ul>
            <li>8.9.1 Hihome has no liability save to the extent admitted by clauses 9.8</li>
            <li>8.9.2 and 9.9.3; 9.9.2 Hihome’s liability to the Host is limited to the amount collected by Hihome as agent of the Host in respect of the Hosted Event to which the relevant claim relates and not paid to the Host (or, where appropriate, refunded to the Guest) in accordance with these T&Cs and any amount recovered under the insurance policy referred to in clause 8.3; and 9.9.3 Hihome’s liability to the Guest is limited to the commission paid to it by the Guest in respect of the Hosted Event to which the relevant claim relates and any amount recovered under the insurance policy referred to in clause 8.3. </li>
        </ul>
        <p>8.10 You agree and confirm that if you choose to use any of the Hihome Websites or the Hihome Services to enter any arrangement with another person (whether in your capacity as a Guest or as a Host) you should enter an agreement with that other person (that agreement may be or comprise the terms and conditions on which the Hihome Invitation is offered and accepted).You agree to adhere to the terms of any such agreement.You acknowledge and agree that you, and not Hihome, are responsible for ensuring that each counter-party to any such agreement complies with the terms of that agreement and satisfies any obligations the counter-party has to you.By agreeing to these T&Cs you also agree that Hihome is not a party to any agreement between you and any other person (whether as Guests, Hosts, agents or in any other capacity) and that (except to the extent that Hihome or any of its agents agrees on and subject to the terms of clause 7 and the other provisions of these T&Cs and as part of the Hihome Services to arrange the collection, holding and payment of Transaction Fees as part of the Hihome Services) Hihome has no liability to you or any other person arising from or related to any agreements between Guests and Hosts. 9.11Subject to the provisions of clause 9, you agree that none of Hihome, its directors, employees, agents or other representatives is liable to you for any damage, whether direct or indirect, resulting from use of the Hihome Websites or the Hihome Services even if Hihome has knowledge or has been informed of the likelihood of the occurrence of such damage.</p>
        <h4>9 Cancellation and suspension</h4>
        <p>9.1 You may terminate your registration at any time by sending us an email from your registered email to info@Hihome.sa</p>
        <p>9.2 Hihome may terminate or suspend your registration for convenience at any time by giving you notice via email to your registered email address.</p>
        <p>9.3 If your Hihome registration is cancelled all Hosted Events in respect of which you had issued Hihome Invitation will be automatically cancelled and all Hosted Events in respect of which you had accepted a Hihome Invitation will also be automatically cancelled.Depending on the applicable cancelation policy, an appropriate refund may be issued.</p>
        <h4>10 Miscellaneous</h4>
        <p>10.1 You declare and guarantee to Hihome that you are a person over 18 years of age and/or having the legal capacity to enter into a contract.</p>
        <p>10.2 Some portions of the Hihome platform implement Google Maps/Earth mapping services, including Google Maps API(s). Your use of Google Maps/Earth is subject to Google’s terms of use.</p>
        <p>10.3 If you become aware of any content on any of the Hihome Websites that you suspect has been posted in breach of these T&Cs please notify us by email at info@Hihome.sa.It will be helpful if you are able to include (a) details of the content concerned, (b) information to enable us to locate the content in question on the Hihome Website, (c) your contact information (full name, postal address, telephone number, email address and, where applicable, the name of the body on whose behalf you are contacting us, its postal address, its registration number), (d) a statement, where applicable, that you are the owner of intellectual property rights or rights to an image or to the person concerned or authorized to act in the name of the owner.</p>
        <p>10.4 You acknowledge and agree that Hihome may store personal and other information about you on your electronic devices in the form of “cookies” and other programs and devices. The use of these solely concerns the functioning of the Hihome Website. You acknowledge and agree that if you do not allow or limit the placing of cookies on your devices, this ban or restriction may have an adverse effect on your use of the Hihome Websites.You acknowledge and agree that Hihome may also store your personal information on computers and servers in Saudi Arabia and beyond its borders. By using the Hihome Website, you acknowledge and agree that Hihome may, at its sole discretion store or divulge this information if required to do so by law or if there are serious reasons to think that storage or divulgence of this information is required to conform to a legal procedure.</p>
        <p>10.5 The publishing director of the Hihome Website is the director of Hihome company Ltd, Mrs. Jean-Michel Petit. The Hihome Website is hosted and managed by Hihome company Ltd.</p>
        <p>10.6 For any question relating to the Hihome Websites or Hihome Services you can contact us by the following means:</p>
        <ul>
            <li>By email: info@Hihome.sa</li>
            <li>By telephone: +966505423361</li>
        </ul>
        <p>10.7 Reference to in these T&Cs to:</p>
        <ul>
            <li>10.7.1 A “person” or “corporation” includes a reference to all legal or natural persons, partnerships, trusts, companies, governments or local authority departments and other bodies and associations (whether corporate or unincorporated);</li>
            <li>10.7.2 An individual includes where appropriate his personal representatives;</li>
            <li>10.7.3 The singular includes a reference to the plural and vice versa;</li>
            <li>10.7.4 One gender includes each gender (feminine, masculine and neuter).</li>
        </ul>
        <p>10.8 References to Hihome in the context of obligations or liabilities owed to Hihome or other benefits or assurances given to Hihome shall be deemed to include reference also to any company which is a subsidiary undertaking of Hihome (“subsidiary undertaking” having the meaning given to it in section 1162 of the Companies Act 2006).</p>
        <p>10.9 No failure or delay by Hihome to exercise any right or remedy under these T&Cs shall be construed as a waiver of that right or remedy nor shall any single or partial exercise of any right or remedy preclude the further exercise of that right or remedy.No waiver by Hihome of any breach of these T&Cs shall be considered as a waiver of a preceding or subsequent breach.The rights and remedies provided in these T&Cs are cumulative and are not exclusive of any rights or remedies provided by law.</p>
        <p>10.10 These T&Cs and the documents referred to in these T&Cs (as in each case updated from time to time) constitute the whole agreement between you and Hihome governing our relations and supersede all other agreements between you and Hihome prior to the date of these T&Cs, which shall cease to have any further effect.</p>
        <p>10.11 If a provision of these T&Cs is held to be illegal or unenforceable, in whole or in part, under an enactment or rule of law, it shall to that extent be deemed not to form part of these T&Cs and the enforceability of the remainder of these T&Cs shall not be affected.</p>
        <p>10.12 Hihome may communicate with you by sending an email or phone message to your registered email address or phone number. It need only adduce proof that the email was sent, and is not responsible for ensuring that you receive it.</p>
        <p>10.13 It is not intended that a third party should have any right to enforce these T&Cs pursuant to the Contracts (Rights of Third Parties) Act 1999 other than that Hihome (being the wider group definition in accordance with clause 11.7) may rely on and enforce these T&Cs as if (in each case) named in these T&Cs in place of Hihome.</p>
        <p>10.14 These T&Cs shall be governed by and construed in accordance with Saudi Arabian law and Hihome and you each agree to submit any dispute, including disputes relating to any non-contractual obligations, which may arise out of, under, or in connection with this agreement to the exclusive jurisdiction of the Saudi Arabian courts.</p>